Repository hamsurang/origin, pull requests merged in 2024-09, with the labels that each got.

#39 docs: sonny 프로필 업데이트
  apps/home/app/(profile-readme)/@profile/people/people.constants.ts
  apps/home/app/(profile-readme)/@readme/_shared/content/sonsurim.mdx
  apps/home/app/(profile-readme)/people/people.constants.ts
Labels: documentation

#42 feat: wiki 페이지 퍼블리싱
  apps/home/app/(profile-readme)/@profile/people/page.tsx
  apps/home/app/(profile-readme)/page.tsx
  apps/home/app/_shared/components/Readme/Readme.tsx
  apps/wiki/app/_shared/components/Docs/Docs.tsx
  apps/wiki/app/_shared/components/Docs/index.ts
  apps/wiki/app/_shared/components/Readme/Readme.tsx
  apps/wiki/app/_shared/components/Readme/index.tsx
  apps/wiki/app/_shared/components/SideNav/SideNav.tsx
  apps/wiki/app/_shared/components/index.ts
  apps/wiki/app/_shared/constants/index.ts
  apps/wiki/app/_shared/constants/nav/nav.constants.ts
  apps/wiki/app/_shared/index.ts
  apps/wiki/app/layout.tsx
  apps/wiki/app/page.tsx
  apps/wiki/middleware.ts
  apps/wiki/next.config.js
  apps/wiki/package.json
  packages/ui/src/components/MDX.styles.tsx
  packages/ui/src/components/index.ts
  packages/utils/src/iframeEventHandler/iframeEventHandler.ts
  packages/utils/src/iframeEventHandler/iframeEventHandler.types.ts
  pnpm-lock.yaml
  web/app/_shared/components/GlobalNavigationBar.tsx
  web/app/home/people/page.tsx
  web/app/wiki/page.tsx
Labels: feature

#43 docs: 퉁이리 MBTI 버그 수정
  apps/home/app/(profile-readme)/people/people.constants.ts
  apps/home/app/_shared/components/MBTIOverview/MBTI.info.tsx
Labels: bug
